{% set name = "beancount" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/beancount-{{ version }}.tar.gz
  sha256: cf6686869c7ea3eefc094ee13ed866bf5f7a2bb0c61e4d4f5df3e35f846cffdf

build:
  entry_points:
    - bean-check = beancount.scripts.check:main
    - bean-doctor = beancount.scripts.doctor:main
    - bean-example = beancount.scripts.example:main
    - bean-format = beancount.scripts.format:main
    - treeify = beancount.tools.treeify:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - meson-python >=0.14.0
    - meson >=1.2.1
    - pip
  run:
    - python
    - click >=7.0
    - python-dateutil >=2.6.0
    - regex >=2022.9.13

test:
  imports:
    - beancount
  commands:
    - pip check
    - bean-check --help
    - bean-doctor --help
    - bean-example --help
    - bean-format --help
    - treeify --help
  requires:
    - pip

about:
  home: https://beancount.github.io/
  summary: Command-line Double-Entry Accounting
  license: GPL-2.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - kklein
